services:
  joplin:
    image: florider89/joplin-server
    container_name: joplin
    restart: unless-stopped
    ports:
      - 8083:80
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      #APP_BASE_URL: "http://localhost:83"
      APP_BASE_URL: "https://personal.codefocus.fun/joplin/user1"
      APP_PORT: 80
      DB_CLIENT: "pg"
      POSTGRES_USER: "joplin"
      POSTGRES_PASSWORD: "rp6mmVPr"
      POSTGRES_HOST: "host.docker.internal"