services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - 8082:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/pi/data/vaultwarden/:/data/
    environment:
      WEBSOCKET_ENABLED: "false"
      ENABLE_DB_WAL: "false"
      #DATABASE_URL: "mysql://vaultwarden:DcS18rEj@host.docker.internal:3306/vaultwarden"
      DATABASE_URL: "postgresql://vaultwarden:ZwyhXED3@host.docker.internal:5432/vaultwarden"
      SIGNUPS_ALLOWED: "false"
      DISABLE_ADMIN_TOKEN: "true"
      #ADMIN_TOKEN: "xVk4ly7yxufaIfzkOZBwqQdKEFyTccqH1IG5d2En7mZpv1oRqZk9XjEqu0J9tUkk"